// SPDX-License-Identifier: GPL-3.0-or-later
package main

import (
	"time"
	"context"
	"net/http"

	pkg "github.com/siamak-amo/v2utils/pkg"
	log "github.com/siamak-amo/v2utils/log"

	core "github.com/xtls/xray-core/core"
	conf "github.com/xtls/xray-core/infra/conf"
	xnet "github.com/xtls/xray-core/common/net"
)

const (
    HTTP_Test_Endpoint = "http://google.com"
)

// Generates a minimal default config for testing
func Set_Default_TestConfig(url string) (*conf.Config) {
	var e error
	var cf *conf.Config
	cf, e = pkg.Gen_main (DEF_Test_Template)
	if nil != e {
		panic (e) // it's ours, not the user.
	}
	return cf
}

func (opt Opt) test_Proxy() bool {
	if e := opt.Run_Xray(); nil != e {
		log.Errorf("Could not run the xray server - %v\n", e)
		return false
	}
	res := opt.test_http();
	opt.Kill_Xray()
	return (res == nil)
}

// This will utilize the xray-core Dial function (DialContext compatible)
func (opt Opt) CustomDial(ctx context.Context, network, addr string) (xnet.Conn, error) {
	__dst, e := xnet.ParseDestination(network + ":" + addr);
	if nil != e {
		return nil, e
	}
	return core.Dial(ctx, opt.Xray_instance, __dst);
}

func (opt Opt) test_http() error {
	httpTransport := &http.Transport{
		DialContext: opt.CustomDial,
	}
	client := &http.Client{
		Transport: httpTransport,
		Timeout:   5 * time.Second,
	}
	_, err := client.Get(HTTP_Test_Endpoint)
	if err != nil {
		log.Infof("Broken VPN :( %v\n", err)
		return err
	}
	return nil
}

// Tests a minimal config generated by Set_Default_TestConfig
// It will not create any local listening proxy, instead
// it passes a simple HTTP request through the running
// xray-core instance @opt.Xray_instance.
func (opt *Opt) Test_URL(url string) bool {
	opt.CFG = Set_Default_TestConfig(url);
	if e := opt.Init_Outbound_byURL(url); nil != e {
		return false
	}
	return opt.test_Proxy();
}

func (opt *Opt) Test_CFG(path string) bool {
	opt.template_file = &path;
	if e := opt.Init_CFG(); nil != e {
		log.Infof("Invalid config file `%s' was ignored.\n", path)
		return false
	}
	return opt.test_Proxy();
}
