// SPDX-License-Identifier: GPL-3.0-or-later
package utils

import (
	"time"
	"context"
	"net/http"

	log "github.com/siamak-amo/v2utils/log"

	core "github.com/xtls/xray-core/core"
	xnet "github.com/xtls/xray-core/common/net"
	conf "github.com/xtls/xray-core/infra/conf"
)

const (
    HTTP_Test_Endpoint = "http://google.com"
)

var (
	TestTimeout time.Duration = 10 * time.Second
)


func (v2 V2utils) doTest() (res bool, duration int64) {
	if e := v2.Run_Xray(); nil != e {
		log.Warnf ("Could not run the xray server - %v\n", e)
		return false, 0
	}
	err, duration := v2.test_http();
	res = (err == nil)
	v2.Kill_Xray()
	return
}

// This will utilize the xray-core Dial function (DialContext compatible)
func (v2 V2utils) CustomDial(ctx context.Context, network, addr string) (xnet.Conn, error) {
	__dst, e := xnet.ParseDestination(network + ":" + addr);
	if nil != e {
		return nil, e
	}
	return core.Dial(ctx, v2.Xray_instance, __dst);
}

func (v2 V2utils) test_http() (res error, duration int64) {
	ctx, cancel := context.WithTimeout (context.Background(), TestTimeout)
	defer cancel()
	req, err := http.NewRequest(http.MethodGet, HTTP_Test_Endpoint, nil)
	if nil != err {
		panic (err) // it's ours, failed to create the test request
	}
	req = req.WithContext(ctx)

	httpTransport := &http.Transport{DialContext: v2.CustomDial}
	client := &http.Client{Transport: httpTransport}
	if _, err := client.Do(req); err != nil {
		log.Infof("Broken VPN :( %v\n", err)
		return err, 0
	}

	deadline, _ := ctx.Deadline()
	return nil, (TestTimeout - time.Until(deadline)).Milliseconds();
}

// Tests a minimal config generated by DEF_Test_Template
// It will not create any local listening proxy, instead
// it passes a simple HTTP request through the running
// xray-core instance @v2.Xray_instance.
func (v2 *V2utils) Test_URL(url string) (result bool, duration int64) {
	v2.Apply_template_bystr(DEF_Test_Template);
	if e := v2.Init_Outbound_byURL(url); nil != e {
		return false, 0
	}
	return v2.doTest();
}

// Tests a config file @path
func (v2 *V2utils) Test_CFG(path string) (result bool, duration int64) {
	if e := v2.Apply_template(path); nil != e || nil == v2.CFG {
		return false, 0
	}

	// We do not use inbound configurations for testing
	// having them may cause true-negative for us
	// as the inbound proxy port(s) might be inuse.
	v2.CFG.InboundConfigs = nil

	// Logs from the instance, may interfere with our logs
	if nil != v2.CFG.LogConfig {
		v2.CFG.LogConfig.LogLevel = "none"
	} else {
		v2.CFG.LogConfig = &conf.LogConfig{LogLevel: "none"}
	}

	return v2.doTest();
}
