// SPDX-License-Identifier: GPL-3.0-or-later
package utils

import (
	"time"
	"context"
	"net/http"

	log "github.com/siamak-amo/v2utils/log"

	core "github.com/xtls/xray-core/core"
	xnet "github.com/xtls/xray-core/common/net"
)

const (
    HTTP_Test_Endpoint = "http://google.com"
)

func (v2 V2utils) doTest() bool {
	if e := v2.Run_Xray(); nil != e {
		log.Warnf ("Could not run the xray server - %v\n", e)
		return false
	}
	res := v2.test_http();
	v2.Kill_Xray()
	return (res == nil)
}

// This will utilize the xray-core Dial function (DialContext compatible)
func (v2 V2utils) CustomDial(ctx context.Context, network, addr string) (xnet.Conn, error) {
	__dst, e := xnet.ParseDestination(network + ":" + addr);
	if nil != e {
		return nil, e
	}
	return core.Dial(ctx, v2.Xray_instance, __dst);
}

func (v2 V2utils) test_http() error {
	httpTransport := &http.Transport{
		DialContext: v2.CustomDial,
	}
	client := &http.Client{
		Transport: httpTransport,
		Timeout:   5 * time.Second,
	}
	_, err := client.Get(HTTP_Test_Endpoint)
	if err != nil {
		log.Infof("Broken VPN :( %v\n", err)
		return err
	}
	return nil
}

// Tests a minimal config generated by Set_Default_TestConfig
// It will not create any local listening proxy, instead
// it passes a simple HTTP request through the running
// xray-core instance @v2.Xray_instance.
func (v2 *V2utils) Test_URL(url string) bool {
	if e := v2.Init_Outbound_byURL(url); nil != e {
		return false
	}
	return v2.doTest();
}

// Tests a config file @path
func (v2 *V2utils) Test_CFG(path string) bool {
	if e := v2.Apply_template(path); nil != e {
		return false
	}

	// We do not use inbound configurations for testing
	// having them may cause true-negative for us
	// as the inbound proxy port(s) might be inuse.
	v2.CFG.InboundConfigs = nil

	// Logs from the instance, may interfere with our logs
	v2.CFG.LogConfig.LogLevel = "none"

	return v2.doTest();
}
