// SPDX-License-Identifier: GPL-3.0-or-later
package utils

import (
	"time"
	"context"
	"net/http"

	log "github.com/siamak-amo/v2utils/log"

	core "github.com/xtls/xray-core/core"
	xnet "github.com/xtls/xray-core/common/net"
	conf "github.com/xtls/xray-core/infra/conf"
)

const (
	// Default test endpoint
	Test_Endpoint_0 = "http://www.google.com"
	// IP address API test endpoints
    Test_Endpoint_1 = "http://api4.ipify.org"
    Test_Endpoint_2 = "http://v4.api.ipinfo.io/ip"
    Test_Endpoint_3 = "http://check-host.net/ip"
    Test_Endpoint_4 = "http://ipv4.icanhazip.com"
)

var (
	TestTimeout time.Duration = 10 * time.Second
)
	// Maximum number of endpoints to test
	TestCount int = 3

	TestEndpoints = []string{
		Test_Endpoint_0,
		Test_Endpoint_1, Test_Endpoint_2, Test_Endpoint_3, Test_Endpoint_4,
	}
)

// @return:  test result (bool),  time duration (int64) in milliseconds
func (v2 V2utils) doTest() (bool, int64) {
	if e := v2.Run_Xray(); nil != e {
		log.Warnf ("Could not run the xray server - %v\n", e)
		return false, 0;
	}

	for n := 0;; {
		for _, endpoint := range TestEndpoints {
			if n += 1; n > TestCount {
				goto give_up;
			}
			if err, time := v2.test_http(endpoint); nil == err {
				return true, time;
			}
		}
	}

give_up:
	v2.Kill_Xray()
	return false, 0;
}

// This will utilize the xray-core Dial function (DialContext compatible)
func (v2 V2utils) CustomDial(ctx context.Context, network, addr string) (xnet.Conn, error) {
	dst, e := xnet.ParseDestination(network + ":" + addr);
	if nil != e {
		return nil, e
	}
	return core.Dial(ctx, v2.Xray_instance, dst);
}

// @addr:  'http://domain.tld'
func (v2 V2utils) test_http(addr string) (res error, duration int64) {
	ctx, cancel := context.WithTimeout (context.Background(), TestTimeout)
	defer cancel()
	req, err := http.NewRequest (http.MethodGet, addr, nil)
	if nil != err {
		return err, 0
	}
	req = req.WithContext(ctx)

	httpTransport := http.Transport{DialContext: v2.CustomDial}
	client := http.Client{Transport: &httpTransport}
	if _, err := client.Do(req); err != nil {
		log.Infof("Broken VPN :( %v\n", err)
		return err, 0
	}

	deadline, _ := ctx.Deadline()
	return nil, (TestTimeout - time.Until(deadline)).Milliseconds();
}

// Tests a minimal config generated by DEF_Test_Template
// It will not create any local listening proxy, instead
// it passes a simple HTTP request through the running
// xray-core instance @v2.Xray_instance.
func (v2 *V2utils) Test_URL(url string) (result bool, duration int64) {
	v2.Apply_template_bystr(DEF_Test_Template);
	if e := v2.Init_Outbound_byURL(url); nil != e {
		return false, 0
	}
	return v2.doTest();
}

// Tests a config file @path
func (v2 *V2utils) Test_CFG(path string) (result bool, duration int64) {
	if e := v2.Apply_template(path); nil != e || nil == v2.CFG {
		return false, 0
	}

	// We do not use inbound configurations for testing
	// having them in config, may cause true-negative for us
	// as the inbound proxy port(s), may be in use.
	v2.CFG.InboundConfigs = nil

	// Logs from the instance, may interfere with our logs
	if nil != v2.CFG.LogConfig {
		v2.CFG.LogConfig.LogLevel = "none"
	} else {
		v2.CFG.LogConfig = &conf.LogConfig{LogLevel: "none"}
	}

	return v2.doTest();
}
